In [1]:
import sklearn
from sklearn.datasets import load_diabetes
from sklearn.ensemble import ExtraTreesRegressor

from mindxlib.post_hoc_explainer import PermutationExplainer

In [4]:
import numpy as np

In [2]:
M = 5 #a user-defined length, represents the number of samples.

In [3]:
data = load_diabetes(as_frame=True)
X,y = data.data, data.target

model = ExtraTreesRegressor() # the model to explain
model.fit(X,y)
explainer = PermutationExplainer(model) # the explainer to explaining the model

In [6]:
Xb = X[:M].to_numpy() # baseline points
Xt = X[M:2*M].to_numpy() # current points
groups = [[0],[1],[2],[3],[4,5,6,7,8,9]] # define the group of features to change together
groups = np.array([np.array(g) for g in groups], dtype=object)
contribs = explainer.explain_instance(Xt,Xb,groups) # compute the contributions of each feature

X does not have valid feature names, but ExtraTreesRegressor was fitted with feature names


In [12]:
# print contributions of each feature.
print(contribs)

[[  3.44924805  18.07665039 -35.7053418   -7.95301758 -31.86753906]
 [  9.5609668   -2.61578125   0.62900391   2.23418945  53.19162109]
 [ -0.4499707    0.         -47.96256836  16.57541016 -46.16287109]
 [ -5.9009082  -21.27224609 -13.84130859  -1.88352539 -53.10201172]
 [ 13.68899414   0.          69.01050781  19.23546875  73.0650293 ]]
